(define (simplify input)
		(define listlength  (+ (length (filter symbol? input)) (length (filter number? input)))) 
		(define symbollength (length (filter symbol? input)))
		(define numberlength (length (filter number? input)))
		(define op1 (car (filter symbol? input))) 
	                (cond
			    ((and (= listlength 3) (= symbollength 1) (= numberlength 2) (equal? op1 '+))  
					(list (car (cdr input)) (car input) (car (cdr (cdr input)))))   
			    ((and (= listlength 3) (= symbollength 2) (= numberlength 1) (equal? op1 '+)) 
			        	(list (car input) (car (cdr (cdr input))) (car (cdr input))))   
			    ((and (= listlength 3) (= symbollength 1) (= numberlength 2) (equal? op1 '*))
					(list (car (cdr input)) (car input) (car (cdr (cdr input)))))   
			    ((and (= listlength 3) (= symbollength 2) (= numberlength 1) (equal? op1 '*))
					(list (car input) (car (cdr (cdr input))) (car (cdr input))))   
			    ((and (= listlength 3) (= symbollength 1) (= numberlength 2) (equal? op1 '-))
					(list (car (cdr input)) (car input) (car (cdr (cdr input)))))   
			    ((and (= listlength 3) (= symbollength 2) (= numberlength 1) (equal? op1 '-))
					(list '+ (append (list (car input)) (list (car (cdr (cdr input))))) (car (cdr input))))   
			    (else
				(cond
				    ((and (= listlength 2) (= symbollength 2) (= numberlength 0) (equal? op1 '+))
					(list (car input) (list (car (car (cddr input)))  (car (cdr input)) (car (cdr (car (cddr input))))) (car (cdr (cdr (car (cddr input)))))))   
				    ((and (= listlength 2) (= symbollength 1) (= numberlength 1) (equal? op1 '+))
			        	(list (car input) (list (car (car (cdr input))) (car (cdr (car (cdr input)))) (car (cddr input))) (car (cdr (cdr (car (cdr input))))))) 
				    ((and (= listlength 2) (= symbollength 1) (= numberlength 1) (equal? op1 '*))
					(list (car (car (cdr input))) (list (car input) (car (cddr input)) (car (cdr (car (cdr input))))) (list (car input) (car (cddr input)) (car (cdr (cdr (car (cdr input)))))))) 
				    ((and (= listlength 2) (= symbollength 2) (= numberlength 0) (equal? op1 '*))
				        (list (car (car (cdr input))) (list (car input) (car (cdr (car (cdr input)))) (car (cddr input))) (list (car input) (car (cdr (cdr (car (cdr input))))) (car (cddr input)))))   
				    (else "Invalid Input")))))
